### PR TITLE
Add support for protein sequences

### PR DESCRIPTION
**Pull request by simone-pignotti**
- Add support for protein sequences (with argument `is_protein=True` passed to `CrazydocParser.parse_doc_file` and `biotools.records_to_genbank`)
- add FASTA export option (to one file only, no annotations; could be complemented by a TSV annotation export)
- fix genbank name (remove `/` since it's used as filename; clip to stay under 20 chars for LOCUS line)

### CODE REVIEW

**Comment by simone-pignotti** [comment]
TODO: add docs and tests

**Comment by Zulko** [comment]
Very cool thanks! I'll wait for the tests and doc update and merge it.

**Comment by simone-pignotti** [comment]
No problem, I will be quite busy in the coming days but I'll try to finish asap

**Comment by veghp** [comment]
Hi @simone-pignotti , thanks for the PR --  I've merged your improvements and added tests + docs in the `dev` branch: https://github.com/Edinburgh-Genome-Foundry/crazydoc/tree/dev

I'll merge to `master` and make a release after an italic-text recognition problem is sorted out.

**Comment by veghp** [comment]
I removed `records_to_fasta()` from `crazydoc/biotools.py` for now, but can be re-added once tests & docs are written for it.

```python
def records_to_fasta(records, filename):
    name_duplicates = {}
    out_records = []
    for record in records:
        name = record.id
        out_record = deepcopy(record)
        if name in name_duplicates:
            name_duplicates[name] += 1
            out_record.id = "%s_%03d" % (name, name_duplicates[name])
        out_records.append(out_record)
    SeqIO.write(out_records, filename, 'fasta')

```

**Comment by simone-pignotti** [comment]
Hey @veghp , sorry I completely forgot about the tests and docs 🙈 thanks for taking care of that!

**Pull request merged**
